backend = "glx";
vsync = true;
shadow = true;
shadow-radius = 14;
shadow-opacity = 0.25;
shadow-offset-x = -6;
shadow-offset-y = -6;
corner-radius = 10;
round-borders = 1;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'"
];
